# BASE RCNN YAML: https://github.com/facebookresearch/detectron2/blob/master/configs/Base-RetinaNet.yaml
# RETINANET: https://github.com/facebookresearch/detectron2/blob/master/configs/COCO-Detection/retinanet_R_50_FPN_3x.yaml

# AUGMENTATION
aug_kwargs:
  HorizontalFlip:
    p: 0.5
  RandomBrightnessContrast:
    p: 0.5

# OPTIMIZER
batch_size: 8
lr_scheduler_name: WarmupCosineLR
base_lr: 0.001
epoch: 10
eval_period_epoch: 3
