# https://www.kaggle.com/corochann/vinbigdata-detectron2-train
# BASE RCNN YAML: https://github.com/facebookresearch/detectron2/blob/master/configs/Base-RCNN-FPN.yaml
# FASTER RCNN: https://github.com/facebookresearch/detectron2/blob/master/MODEL_ZOO.md#faster-r-cnn

# AUGMENTATION
aug_kwargs:
  HorizontalFlip:
    p: 0.4
  RandomBrightnessContrast:
    p: 0.4

# OPTIMIZER
batch_size: 8
lr_scheduler_name: WarmupCosineLR
base_lr: 0.0001
epoch: 30
eval_period_epoch: 6
